name: Deployment
description: Code Deployment
title: ":rocket: deploy : "
labels: ["deployment"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Content
      description: Please describe the changes related to the deployment.
      value: |
        -
    validations:
      required: true
